source 'https://rubygems.org'

ruby '2.2.3'
gem 'rails', '4.2.5.2'
gem 'heroku_san'
gem 'nokogiri'
gem 'mysql2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'faraday'
gem 'faraday_middleware'
gem 'rails_admin'
gem 'rspec-rails', '>= 3.3'

group :development, :test do
  gem 'byebug'
  gem 'factory_girl_rails'
  gem 'jasmine'
  gem 'jasmine-rails', '~> 0.9.1' # One of these 2 does not seem to support phantom js
  gem 'jasmine-jquery-rails', '~> 1.5.9'# One of these 2 does not seem to support phantom js
end

group :test do
  gem 'webmock'
end

group :development do
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end